#baseurl: "http://xaverfuchs.de/"
#baseurl: "/Users/xaverfuchs/Documents/Website/xaverfuchs2021Research/xaverfuchsde/docs/"
#baseurl: "./"
baseurl: "https://xaverfuchs.github.io/xaverfuchsde/"
relativeURLs: true
canonifyURLs: true
publishDir: "./docs"
languageCode: "en-us"
title: "Xaver Fuchs Research"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Bio
      url: "bio/"
      weight: 2
    - name: Blog
      url: "blog/"
      weight: 3
    - name: Research
      url: "research/"
      weight: 4
    - name: Music
      url: "musicandarts/"
      weight: 5

params:
  description: "Research website of Xaver Fuchs"
  footer: "&copy; [Xaver Fuchs](www.xaverfuchs.de) 2021 -- {Year} | [Github](https://github.com/xaverfuchs) | [Bluesky](https://bsky.app/profile/xaverfuchs.bsky.social)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
